/**
 * Puzzle piece catalog — maximized library; every kind has a Worker evaluator.
 */
import type { Timeframe } from '@/types/ui';
import type {
  PieceCategory,
  PieceKind,
  PieceParams,
} from '@/strategy/graphTypes';

export type ParamFieldType = 'number' | 'select' | 'boolean';

export interface ParamField {
  key: string;
  label: string;
  type: ParamFieldType;
  min?: number;
  max?: number;
  step?: number;
  options?: { value: string; label: string }[];
}

export interface PieceDefinition {
  kind: PieceKind;
  label: string;
  shortLabel: string;
  category: PieceCategory;
  description: string;
  defaultRequiredTimeframe: Timeframe | null;
  maxInputs: number;
  params: ParamField[];
  defaults: PieceParams;
}

const SIDE_OPTIONS = [
  { value: 'buy', label: 'Buy / long' },
  { value: 'sell', label: 'Sell / short' },
  { value: 'either', label: 'Either' },
];
const REF_OPTIONS = [
  { value: 'close', label: 'Close' },
  { value: 'high', label: 'High' },
  { value: 'low', label: 'Low' },
];
const MA_TYPE = [
  { value: 'sma', label: 'SMA' },
  { value: 'ema', label: 'EMA' },
];
const KZ_OPTIONS = [
  { value: 'london', label: 'London (07–10 UTC)' },
  { value: 'ny', label: 'New York (12–15 UTC)' },
  { value: 'london_ny', label: 'London + NY' },
  { value: 'asia', label: 'Asia (00–05 UTC)' },
];
const CHOP_MODE = [
  { value: 'trend', label: 'Trend (Chop low)' },
  { value: 'range', label: 'Range (Chop high)' },
];
const FIB_LEVELS = [
  { value: '38.2', label: '38.2%' },
  { value: '50', label: '50%' },
  { value: '61.8', label: '61.8%' },
  { value: '78.6', label: '78.6%' },
];
const DOW_OPTIONS = [
  { value: '1', label: 'Monday' },
  { value: '2', label: 'Tuesday' },
  { value: '3', label: 'Wednesday' },
  { value: '4', label: 'Thursday' },
  { value: '5', label: 'Friday' },
];

function sideParam(): ParamField {
  return { key: 'side', label: 'Side', type: 'select', options: SIDE_OPTIONS };
}

export const PIECE_REGISTRY: PieceDefinition[] = [

  {
    kind: 'and',
    label: 'AND',
    shortLabel: 'AND',
    category: 'logic',
    description: 'All connected inputs must be true.',
    defaultRequiredTimeframe: null,
    maxInputs: 8,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'or',
    label: 'OR',
    shortLabel: 'OR',
    category: 'logic',
    description: 'Any connected input may be true.',
    defaultRequiredTimeframe: null,
    maxInputs: 8,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'not',
    label: 'NOT',
    shortLabel: 'NOT',
    category: 'logic',
    description: 'Inverts a single input.',
    defaultRequiredTimeframe: null,
    maxInputs: 1,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'xor',
    label: 'XOR',
    shortLabel: 'XOR',
    category: 'logic',
    description: 'Exactly one of two inputs is true.',
    defaultRequiredTimeframe: null,
    maxInputs: 2,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'sma_cross',
    label: 'SMA cross',
    shortLabel: 'SMA×',
    category: 'indicator',
    description: 'SMA cross: fast crosses slow.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 200, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 3, max: 400, step: 1 },
      sideParam(),
    ],
    defaults: { fastPeriod: 10, slowPeriod: 30, side: 'either' },
  },
  {
    kind: 'ema_cross',
    label: 'EMA cross',
    shortLabel: 'EMA×',
    category: 'indicator',
    description: 'EMA cross: fast crosses slow.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 200, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 3, max: 400, step: 1 },
      sideParam(),
    ],
    defaults: { fastPeriod: 9, slowPeriod: 21, side: 'either' },
  },
  {
    kind: 'wma_cross',
    label: 'WMA cross',
    shortLabel: 'WMA×',
    category: 'indicator',
    description: 'WMA cross: fast crosses slow.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 200, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 3, max: 400, step: 1 },
      sideParam(),
    ],
    defaults: { fastPeriod: 10, slowPeriod: 30, side: 'either' },
  },
  {
    kind: 'hma_cross',
    label: 'HMA cross',
    shortLabel: 'HMA×',
    category: 'indicator',
    description: 'HMA cross: fast crosses slow.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 200, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 3, max: 400, step: 1 },
      sideParam(),
    ],
    defaults: { fastPeriod: 9, slowPeriod: 16, side: 'either' },
  },
  {
    kind: 'donchian_break',
    label: 'Donchian break',
    shortLabel: 'Don',
    category: 'indicator',
    description: 'Break of N-bar high/low.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 2, max: 200, step: 1 },
      sideParam(),
    ],
    defaults: { period: 20, side: 'either' },
  },
  {
    kind: 'rsi_gate',
    label: 'RSI gate',
    shortLabel: 'RSI',
    category: 'indicator',
    description: 'RSI below/above a level.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 2, max: 100, step: 1 },
      { key: 'level', label: 'Level', type: 'number', min: 1, max: 99, step: 1 },
      sideParam(),
    ],
    defaults: { period: 14, level: 30, side: 'buy' },
  },
  {
    kind: 'rsi_cross',
    label: 'RSI cross level',
    shortLabel: 'RSI×',
    category: 'indicator',
    description: 'RSI crosses a level.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 2, max: 100, step: 1 },
      { key: 'level', label: 'Level', type: 'number', min: 1, max: 99, step: 1 },
      sideParam(),
    ],
    defaults: { period: 14, level: 50, side: 'either' },
  },
  {
    kind: 'macd_cross',
    label: 'MACD cross',
    shortLabel: 'MACD',
    category: 'indicator',
    description: 'MACD crosses signal.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 50, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'signalPeriod', label: 'Signal', type: 'number', min: 2, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { fastPeriod: 12, slowPeriod: 26, signalPeriod: 9, side: 'either' },
  },
  {
    kind: 'macd_hist_flip',
    label: 'MACD hist flip',
    shortLabel: 'MACDh',
    category: 'indicator',
    description: 'MACD histogram flips sign.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 50, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'signalPeriod', label: 'Signal', type: 'number', min: 2, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { fastPeriod: 12, slowPeriod: 26, signalPeriod: 9, side: 'either' },
  },
  {
    kind: 'bb_touch',
    label: 'Bollinger touch',
    shortLabel: 'BB',
    category: 'indicator',
    description: 'Close pierces BB band.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'stdDev', label: 'StdDev', type: 'number', min: 1, max: 4, step: 0.1 },
      sideParam(),
    ],
    defaults: { period: 20, stdDev: 2, side: 'either' },
  },
  {
    kind: 'bb_squeeze',
    label: 'BB squeeze',
    shortLabel: 'BBsq',
    category: 'indicator',
    description: 'Bandwidth compresses then expands.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'stdDev', label: 'StdDev', type: 'number', min: 1, max: 4, step: 0.1 },
      { key: 'lookback', label: 'Lookback', type: 'number', min: 5, max: 50, step: 1 },
    ],
    defaults: { period: 20, stdDev: 2, lookback: 20 },
  },
  {
    kind: 'bb_walk',
    label: 'BB walk',
    shortLabel: 'BBwk',
    category: 'indicator',
    description: 'Close walks outside bands.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'stdDev', label: 'StdDev', type: 'number', min: 1, max: 4, step: 0.1 },
      { key: 'bars', label: 'Bars', type: 'number', min: 2, max: 5, step: 1 },
      sideParam(),
    ],
    defaults: { period: 20, stdDev: 2, bars: 2, side: 'either' },
  },
  {
    kind: 'keltner_break',
    label: 'Keltner break',
    shortLabel: 'KC',
    category: 'indicator',
    description: 'Close breaks Keltner channel.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'mult', label: 'ATR mult', type: 'number', min: 1, max: 4, step: 0.1 },
      sideParam(),
    ],
    defaults: { period: 20, mult: 1.5, side: 'either' },
  },
  {
    kind: 'envelopes_touch',
    label: 'Envelopes touch',
    shortLabel: 'Env',
    category: 'indicator',
    description: 'Close touches MA envelope.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 200, step: 1 },
      { key: 'percent', label: 'Percent', type: 'number', min: 0.1, max: 5, step: 0.1 },
      sideParam(),
    ],
    defaults: { period: 20, percent: 1, side: 'either' },
  },
  {
    kind: 'price_vs_ma',
    label: 'Price vs MA',
    shortLabel: 'Px/MA',
    category: 'indicator',
    description: 'Close crosses MA.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 2, max: 400, step: 1 },
      { key: 'maType', label: 'MA type', type: 'select', options: MA_TYPE },
      sideParam(),
    ],
    defaults: { period: 50, maType: 'ema', side: 'either' },
  },
  {
    kind: 'ma_stack',
    label: 'MA stack',
    shortLabel: 'Stack',
    category: 'indicator',
    description: 'Price and MAs aligned (bull/bear stack).',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 100, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 5, max: 400, step: 1 },
      { key: 'maType', label: 'MA type', type: 'select', options: MA_TYPE },
      sideParam(),
    ],
    defaults: { fastPeriod: 20, slowPeriod: 50, maType: 'ema', side: 'buy' },
  },
  {
    kind: 'ma_slope',
    label: 'MA slope',
    shortLabel: 'Slope',
    category: 'indicator',
    description: 'MA rising/falling over N bars.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 2, max: 200, step: 1 },
      { key: 'slopeBars', label: 'Slope bars', type: 'number', min: 1, max: 20, step: 1 },
      { key: 'maType', label: 'MA type', type: 'select', options: MA_TYPE },
      sideParam(),
    ],
    defaults: { period: 20, slopeBars: 3, maType: 'ema', side: 'either' },
  },
  {
    kind: 'stoch_cross',
    label: 'Stochastic cross',
    shortLabel: 'Stoch',
    category: 'indicator',
    description: '%K crosses %D near extremes.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'kPeriod', label: '%K', type: 'number', min: 3, max: 40, step: 1 },
      { key: 'dPeriod', label: '%D', type: 'number', min: 1, max: 20, step: 1 },
      { key: 'obLevel', label: 'OB', type: 'number', min: 50, max: 95, step: 1 },
      { key: 'osLevel', label: 'OS', type: 'number', min: 5, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { kPeriod: 14, dPeriod: 3, obLevel: 80, osLevel: 20, side: 'either' },
  },
  {
    kind: 'stoch_gate',
    label: 'Stochastic gate',
    shortLabel: 'StochG',
    category: 'indicator',
    description: '%K in oversold/overbought.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'kPeriod', label: '%K', type: 'number', min: 3, max: 40, step: 1 },
      { key: 'obLevel', label: 'OB', type: 'number', min: 50, max: 95, step: 1 },
      { key: 'osLevel', label: 'OS', type: 'number', min: 5, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { kPeriod: 14, obLevel: 80, osLevel: 20, side: 'buy' },
  },
  {
    kind: 'atr_surge',
    label: 'ATR surge',
    shortLabel: 'ATR↑',
    category: 'indicator',
    description: 'ATR expands vs its average.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'ATR period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'mult', label: 'vs avg ×', type: 'number', min: 1.1, max: 4, step: 0.1 },
    ],
    defaults: { period: 14, mult: 1.5 },
  },
  {
    kind: 'atr_compress',
    label: 'ATR compress',
    shortLabel: 'ATR↓',
    category: 'indicator',
    description: 'ATR below average (quiet).',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'ATR period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'mult', label: 'vs avg ×', type: 'number', min: 0.2, max: 1, step: 0.05 },
    ],
    defaults: { period: 14, mult: 0.7 },
  },
  {
    kind: 'momentum',
    label: 'Momentum / ROC',
    shortLabel: 'ROC',
    category: 'indicator',
    description: 'ROC crosses zero.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 2, max: 100, step: 1 },
      sideParam(),
    ],
    defaults: { period: 10, side: 'either' },
  },
  {
    kind: 'roc_extreme',
    label: 'ROC extreme',
    shortLabel: 'ROCx',
    category: 'indicator',
    description: 'ROC beyond threshold.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 2, max: 100, step: 1 },
      { key: 'threshold', label: 'Threshold %', type: 'number', min: 0.1, max: 10, step: 0.1 },
      sideParam(),
    ],
    defaults: { period: 10, threshold: 1, side: 'either' },
  },
  {
    kind: 'cci_gate',
    label: 'CCI gate',
    shortLabel: 'CCI',
    category: 'indicator',
    description: 'CCI beyond ±level.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'level', label: 'Level', type: 'number', min: 50, max: 300, step: 1 },
      sideParam(),
    ],
    defaults: { period: 20, level: 100, side: 'either' },
  },
  {
    kind: 'cci_cross',
    label: 'CCI cross',
    shortLabel: 'CCI×',
    category: 'indicator',
    description: 'CCI crosses zero or level.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'level', label: 'Level', type: 'number', min: 0, max: 200, step: 1 },
      sideParam(),
    ],
    defaults: { period: 20, level: 0, side: 'either' },
  },
  {
    kind: 'willr_gate',
    label: 'Williams %R',
    shortLabel: '%R',
    category: 'indicator',
    description: '%R oversold/overbought.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'osLevel', label: 'OS', type: 'number', min: -100, max: -50, step: 1 },
      { key: 'obLevel', label: 'OB', type: 'number', min: -50, max: 0, step: 1 },
      sideParam(),
    ],
    defaults: { period: 14, osLevel: -80, obLevel: -20, side: 'buy' },
  },
  {
    kind: 'adx_trend',
    label: 'ADX trend',
    shortLabel: 'ADX',
    category: 'indicator',
    description: 'ADX above level (trending).',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'level', label: 'Level', type: 'number', min: 10, max: 50, step: 1 },
    ],
    defaults: { period: 14, level: 25 },
  },
  {
    kind: 'ao_cross',
    label: 'AO cross',
    shortLabel: 'AO',
    category: 'indicator',
    description: 'Awesome Oscillator crosses zero.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'supertrend_flip',
    label: 'Supertrend flip',
    shortLabel: 'ST',
    category: 'indicator',
    description: 'Close flips vs Supertrend.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'ATR period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'mult', label: 'Mult', type: 'number', min: 1, max: 5, step: 0.1 },
      sideParam(),
    ],
    defaults: { period: 10, mult: 3, side: 'either' },
  },
  {
    kind: 'psar_flip',
    label: 'PSAR flip',
    shortLabel: 'PSAR',
    category: 'indicator',
    description: 'Parabolic SAR flips side.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'step', label: 'Step', type: 'number', min: 0.01, max: 0.1, step: 0.01 },
      { key: 'max', label: 'Max', type: 'number', min: 0.1, max: 0.5, step: 0.01 },
      sideParam(),
    ],
    defaults: { step: 0.02, max: 0.2, side: 'either' },
  },
  {
    kind: 'ichimoku_tk_cross',
    label: 'Ichimoku TK cross',
    shortLabel: 'TK×',
    category: 'indicator',
    description: 'Tenkan crosses Kijun.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'tenkan', label: 'Tenkan', type: 'number', min: 5, max: 30, step: 1 },
      { key: 'kijun', label: 'Kijun', type: 'number', min: 10, max: 60, step: 1 },
      sideParam(),
    ],
    defaults: { tenkan: 9, kijun: 26, side: 'either' },
  },
  {
    kind: 'ichimoku_cloud',
    label: 'Ichimoku cloud',
    shortLabel: 'Cloud',
    category: 'indicator',
    description: 'Close breaks into/out of cloud.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'tenkan', label: 'Tenkan', type: 'number', min: 5, max: 30, step: 1 },
      { key: 'kijun', label: 'Kijun', type: 'number', min: 10, max: 60, step: 1 },
      { key: 'senkou', label: 'Senkou', type: 'number', min: 20, max: 120, step: 1 },
      sideParam(),
    ],
    defaults: { tenkan: 9, kijun: 26, senkou: 52, side: 'either' },
  },
  {
    kind: 'trix_cross',
    label: 'TRIX cross',
    shortLabel: 'TRIX',
    category: 'indicator',
    description: 'TRIX crosses zero.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { period: 15, side: 'either' },
  },
  {
    kind: 'ppo_cross',
    label: 'PPO cross',
    shortLabel: 'PPO',
    category: 'indicator',
    description: 'PPO crosses signal.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', min: 2, max: 50, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'signalPeriod', label: 'Signal', type: 'number', min: 2, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { fastPeriod: 12, slowPeriod: 26, signalPeriod: 9, side: 'either' },
  },
  {
    kind: 'aroon_cross',
    label: 'Aroon cross',
    shortLabel: 'Aroon',
    category: 'indicator',
    description: 'Aroon Up crosses Down.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { period: 25, side: 'either' },
  },
  {
    kind: 'chop_filter',
    label: 'Chop filter',
    shortLabel: 'Chop',
    category: 'indicator',
    description: 'Choppiness below (trend) or above (range).',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'period', label: 'Period', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'level', label: 'Level', type: 'number', min: 30, max: 70, step: 1 },
      { key: 'mode', label: 'Mode', type: 'select', options: CHOP_MODE },
    ],
    defaults: { period: 14, level: 38.2, mode: 'trend' },
  },
  {
    kind: 'candle_confirm',
    label: 'Candle confirm',
    shortLabel: 'Candle',
    category: 'price',
    description: 'N consecutive advancing/declining bars.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'bars', label: 'Bars', type: 'number', min: 1, max: 5, step: 1 },
      { key: 'ref', label: 'Reference', type: 'select', options: REF_OPTIONS },
      sideParam(),
    ],
    defaults: { bars: 2, ref: 'close', side: 'buy' },
  },
  {
    kind: 'engulfing',
    label: 'Engulfing',
    shortLabel: 'Engulf',
    category: 'price',
    description: 'Body engulfs prior body.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'pin_bar',
    label: 'Pin bar',
    shortLabel: 'Pin',
    category: 'price',
    description: 'Long wick rejection.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'wickRatio', label: 'Wick × body', type: 'number', min: 1.5, max: 5, step: 0.1 },
      sideParam(),
    ],
    defaults: { wickRatio: 2, side: 'either' },
  },
  {
    kind: 'inside_bar',
    label: 'Inside bar',
    shortLabel: 'Inside',
    category: 'price',
    description: 'Range inside prior bar.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'outside_bar',
    label: 'Outside bar',
    shortLabel: 'Outside',
    category: 'price',
    description: 'Engulfs prior high/low.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'doji',
    label: 'Doji',
    shortLabel: 'Doji',
    category: 'price',
    description: 'Tiny body vs range.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'bodyPct', label: 'Max body %', type: 'number', min: 1, max: 25, step: 1 },
    ],
    defaults: { bodyPct: 10 },
  },
  {
    kind: 'gap',
    label: 'Gap',
    shortLabel: 'Gap',
    category: 'price',
    description: 'Open gaps prior extreme.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'body_direction',
    label: 'Bull / bear candle',
    shortLabel: 'Body',
    category: 'price',
    description: 'Close vs open.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'buy' },
  },
  {
    kind: 'hh_ll',
    label: 'HH / LL',
    shortLabel: 'HH/LL',
    category: 'price',
    description: 'Higher high or lower low.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 2, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 5, side: 'either' },
  },
  {
    kind: 'hl_lh',
    label: 'HL / LH',
    shortLabel: 'HL/LH',
    category: 'price',
    description: 'Higher low or lower high.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 2, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 5, side: 'either' },
  },
  {
    kind: 'session_range_break',
    label: 'Day open-range break',
    shortLabel: 'ORB',
    category: 'price',
    description: 'Break first N bars of UTC day.',
    defaultRequiredTimeframe: '5m',
    maxInputs: 0,
    params: [
      { key: 'rangeBars', label: 'Range bars', type: 'number', min: 1, max: 60, step: 1 },
      sideParam(),
    ],
    defaults: { rangeBars: 6, side: 'either' },
  },
  {
    kind: 'morning_star',
    label: 'Morning star',
    shortLabel: 'MStar',
    category: 'price',
    description: '3-bar bullish reversal.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'evening_star',
    label: 'Evening star',
    shortLabel: 'EStar',
    category: 'price',
    description: '3-bar bearish reversal.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'three_soldiers',
    label: 'Three soldiers',
    shortLabel: 'Soldiers',
    category: 'price',
    description: '3 strong bullish closes.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'three_crows',
    label: 'Three crows',
    shortLabel: 'Crows',
    category: 'price',
    description: '3 strong bearish closes.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
    ],
    defaults: {},
  },
  {
    kind: 'harami',
    label: 'Harami',
    shortLabel: 'Harami',
    category: 'price',
    description: 'Inside body reversal.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'piercing_dark',
    label: 'Piercing / dark cloud',
    shortLabel: 'Pierce',
    category: 'price',
    description: '2-bar reverse through midpoint.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'marubozu',
    label: 'Marubozu',
    shortLabel: 'Maru',
    category: 'price',
    description: 'Almost no wicks, strong body.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'spinning_top',
    label: 'Spinning top',
    shortLabel: 'Spin',
    category: 'price',
    description: 'Small body, long wicks.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'bodyPct', label: 'Max body %', type: 'number', min: 5, max: 40, step: 1 },
    ],
    defaults: { bodyPct: 30 },
  },
  {
    kind: 'tweezer',
    label: 'Tweezer',
    shortLabel: 'Tweezer',
    category: 'price',
    description: 'Matching highs or lows.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'tolerancePct', label: 'Tol %', type: 'number', min: 0.01, max: 0.5, step: 0.01 },
      sideParam(),
    ],
    defaults: { tolerancePct: 0.05, side: 'either' },
  },
  {
    kind: 'nr_bar',
    label: 'Narrow range (NR)',
    shortLabel: 'NR',
    category: 'price',
    description: 'Narrowest range in N bars.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 4, max: 20, step: 1 },
    ],
    defaults: { lookback: 7 },
  },
  {
    kind: 'wide_range_bar',
    label: 'Wide range bar',
    shortLabel: 'WRB',
    category: 'price',
    description: 'Range >> average.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'mult', label: '× avg', type: 'number', min: 1.5, max: 5, step: 0.1 },
      sideParam(),
    ],
    defaults: { lookback: 14, mult: 2, side: 'either' },
  },
  {
    kind: 'close_in_range',
    label: 'Close in range',
    shortLabel: 'ClRng',
    category: 'price',
    description: 'Close in top/bottom of bar.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'pct', label: 'Zone %', type: 'number', min: 10, max: 40, step: 1 },
      sideParam(),
    ],
    defaults: { pct: 25, side: 'buy' },
  },
  {
    kind: 'rejection_wick',
    label: 'Rejection wick',
    shortLabel: 'Reject',
    category: 'price',
    description: 'Wick ≥ ratio of range.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'wickPct', label: 'Wick %', type: 'number', min: 40, max: 90, step: 1 },
      sideParam(),
    ],
    defaults: { wickPct: 60, side: 'either' },
  },
  {
    kind: 'two_bar_reversal',
    label: 'Two-bar reversal',
    shortLabel: '2BR',
    category: 'price',
    description: 'Outside reverse close.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'fvg',
    label: 'Fair value gap',
    shortLabel: 'FVG',
    category: 'structure',
    description: '3-candle imbalance touch.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      sideParam(),
      { key: 'lookback', label: 'Lookback', type: 'number', min: 3, max: 100, step: 1 },
    ],
    defaults: { side: 'buy', lookback: 20 },
  },
  {
    kind: 'ifvg',
    label: 'Inversion FVG',
    shortLabel: 'IFVG',
    category: 'structure',
    description: 'Traded-through FVG revisit.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      sideParam(),
      { key: 'lookback', label: 'Lookback', type: 'number', min: 3, max: 100, step: 1 },
    ],
    defaults: { side: 'buy', lookback: 20 },
  },
  {
    kind: 'ote_touch',
    label: 'OTE touch',
    shortLabel: 'OTE',
    category: 'structure',
    description: '62–79% swing retrace.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'swingLookback', label: 'Swing bars', type: 'number', min: 5, max: 100, step: 1 },
      sideParam(),
    ],
    defaults: { swingLookback: 20, side: 'buy' },
  },
  {
    kind: 'bos_choch',
    label: 'BOS / CHoCH',
    shortLabel: 'BOS',
    category: 'structure',
    description: 'Break prior swing.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'swingLookback', label: 'Swing bars', type: 'number', min: 3, max: 80, step: 1 },
      sideParam(),
    ],
    defaults: { swingLookback: 10, side: 'either' },
  },
  {
    kind: 'liquidity_sweep',
    label: 'Liquidity sweep',
    shortLabel: 'Sweep',
    category: 'structure',
    description: 'Wick beyond extreme, close inside.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 3, max: 50, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 10, side: 'either' },
  },
  {
    kind: 'equal_highs_lows',
    label: 'Equal highs / lows',
    shortLabel: 'EQH/L',
    category: 'structure',
    description: 'Near-equal highs/lows.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 5, max: 80, step: 1 },
      { key: 'tolerancePct', label: 'Tol %', type: 'number', min: 0.01, max: 0.5, step: 0.01 },
      sideParam(),
    ],
    defaults: { lookback: 20, tolerancePct: 0.05, side: 'either' },
  },
  {
    kind: 'order_block',
    label: 'Order block',
    shortLabel: 'OB',
    category: 'structure',
    description: 'Last opposing bar before impulse.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 5, max: 80, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 20, side: 'buy' },
  },
  {
    kind: 'displacement',
    label: 'Displacement',
    shortLabel: 'Disp',
    category: 'structure',
    description: 'Impulsive range vs average.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Avg bars', type: 'number', min: 5, max: 50, step: 1 },
      { key: 'mult', label: '× avg', type: 'number', min: 1.5, max: 5, step: 0.1 },
      sideParam(),
    ],
    defaults: { lookback: 14, mult: 2, side: 'either' },
  },
  {
    kind: 'breaker_block',
    label: 'Breaker block',
    shortLabel: 'BRK',
    category: 'structure',
    description: 'Failed order block flipped.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 5, max: 80, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 20, side: 'buy' },
  },
  {
    kind: 'premium_discount',
    label: 'Premium / discount',
    shortLabel: 'P/D',
    category: 'structure',
    description: 'Above/below 50% of swing.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'swingLookback', label: 'Swing bars', type: 'number', min: 5, max: 100, step: 1 },
      sideParam(),
    ],
    defaults: { swingLookback: 20, side: 'buy' },
  },
  {
    kind: 'fib_touch',
    label: 'Fib touch',
    shortLabel: 'Fib',
    category: 'structure',
    description: 'Touch 38.2 / 50 / 61.8 of swing.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'swingLookback', label: 'Swing bars', type: 'number', min: 5, max: 100, step: 1 },
      { key: 'level', label: 'Fib', type: 'select', options: FIB_LEVELS },
      sideParam(),
    ],
    defaults: { swingLookback: 20, level: '61.8', side: 'buy' },
  },
  {
    kind: 'retest_break',
    label: 'Retest of break',
    shortLabel: 'Retest',
    category: 'structure',
    description: 'Break then retest hold.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 5, max: 40, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 10, side: 'either' },
  },
  {
    kind: 'swing_failure',
    label: 'Swing failure',
    shortLabel: 'SFP',
    category: 'structure',
    description: 'Failed break of swing.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 5, max: 40, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 10, side: 'either' },
  },
  {
    kind: 'untapped_extreme',
    label: 'Untapped extreme',
    shortLabel: 'Untap',
    category: 'structure',
    description: 'Prior extreme not revisited.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'lookback', label: 'Lookback', type: 'number', min: 10, max: 100, step: 1 },
      sideParam(),
    ],
    defaults: { lookback: 30, side: 'either' },
  },
  {
    kind: 'mss',
    label: 'Market structure shift',
    shortLabel: 'MSS',
    category: 'structure',
    description: 'Break + close beyond swing.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      { key: 'swingLookback', label: 'Swing bars', type: 'number', min: 3, max: 80, step: 1 },
      sideParam(),
    ],
    defaults: { swingLookback: 12, side: 'either' },
  },
  {
    kind: 'killzone',
    label: 'Killzone window',
    shortLabel: 'KZ',
    category: 'session',
    description: 'UTC killzone filter.',
    defaultRequiredTimeframe: '5m',
    maxInputs: 0,
    params: [
      { key: 'zone', label: 'Zone', type: 'select', options: KZ_OPTIONS },
    ],
    defaults: { zone: 'london' },
  },
  {
    kind: 'asian_range_break',
    label: 'Asian range break',
    shortLabel: 'Asia',
    category: 'session',
    description: 'Break 00–08 UTC range.',
    defaultRequiredTimeframe: '5m',
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'london_open_break',
    label: 'London open break',
    shortLabel: 'Ldn',
    category: 'session',
    description: 'Break first hour after 07 UTC.',
    defaultRequiredTimeframe: '5m',
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'ny_open_break',
    label: 'NY open break',
    shortLabel: 'NY',
    category: 'session',
    description: 'Break first hour after 12 UTC.',
    defaultRequiredTimeframe: '5m',
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'prev_day_hl',
    label: 'Prev day H/L break',
    shortLabel: 'PDH/L',
    category: 'session',
    description: 'Break prior UTC day high/low.',
    defaultRequiredTimeframe: '15m',
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'prev_week_hl',
    label: 'Prev week H/L break',
    shortLabel: 'PWH/L',
    category: 'session',
    description: 'Break prior week high/low.',
    defaultRequiredTimeframe: '1h',
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'week_open_break',
    label: 'Week open break',
    shortLabel: 'WOpen',
    category: 'session',
    description: 'Break Monday open.',
    defaultRequiredTimeframe: '1h',
    maxInputs: 0,
    params: [
      sideParam(),
    ],
    defaults: { side: 'either' },
  },
  {
    kind: 'round_number',
    label: 'Round number',
    shortLabel: 'Round',
    category: 'session',
    description: 'Touch psychological level.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'step', label: 'Step', type: 'number', min: 0.0001, max: 100, step: 0.0001 },
      sideParam(),
    ],
    defaults: { step: 0.01, side: 'either' },
  },
  {
    kind: 'day_of_week',
    label: 'Day of week',
    shortLabel: 'DOW',
    category: 'session',
    description: 'True on selected UTC weekday.',
    defaultRequiredTimeframe: null,
    maxInputs: 0,
    params: [
      { key: 'day', label: 'Day', type: 'select', options: DOW_OPTIONS },
    ],
    defaults: { day: '1' },
  },
  {
    kind: 'hour_window',
    label: 'Hour window',
    shortLabel: 'Hours',
    category: 'session',
    description: 'True in UTC hour range.',
    defaultRequiredTimeframe: '5m',
    maxInputs: 0,
    params: [
      { key: 'fromHour', label: 'From', type: 'number', min: 0, max: 23, step: 1 },
      { key: 'toHour', label: 'To', type: 'number', min: 1, max: 24, step: 1 },
    ],
    defaults: { fromHour: 7, toHour: 10 },
  },
];

const BY_KIND = new Map(PIECE_REGISTRY.map((p) => [p.kind, p]));

export function getPieceDef(kind: PieceKind): PieceDefinition | undefined {
  return BY_KIND.get(kind);
}

export function isLogicKind(kind: PieceKind): boolean {
  return kind === 'and' || kind === 'or' || kind === 'not' || kind === 'xor';
}

export const PIECE_CATEGORIES: { id: PieceCategory; label: string }[] = [
  { id: 'logic', label: 'Logic' },
  { id: 'price', label: 'Price / candle' },
  { id: 'indicator', label: 'Indicators' },
  { id: 'structure', label: 'Structure' },
  { id: 'session', label: 'Session' },
];

export function createPieceData(kind: PieceKind): {
  pieceKind: PieceKind;
  label: string;
  params: PieceParams;
  requiredTimeframe: Timeframe | null;
} {
  const def = getPieceDef(kind);
  if (!def) {
    return { pieceKind: kind, label: kind, params: {}, requiredTimeframe: null };
  }
  return {
    pieceKind: kind,
    label: def.label,
    params: { ...def.defaults },
    requiredTimeframe: def.defaultRequiredTimeframe,
  };
}

/** All non-logic condition kinds (for completeness checks). */
export function allConditionKinds(): PieceKind[] {
  return PIECE_REGISTRY.filter((p) => !isLogicKind(p.kind)).map((p) => p.kind);
}
