import type { IndicatorDef, IndicatorId, ParamField } from '@/types/indicator';

const period = (defaultPeriod = 14, max = 500): ParamField => {
  void defaultPeriod;
  return {
    key: 'period',
    label: 'Period',
    type: 'number',
    min: 1,
    max,
    step: 1,
  };
};

const numField = (
  key: string,
  label: string,
  defaultValue: number,
  min = 0,
  max = 500,
  step = 1,
): ParamField => {
  void defaultValue;
  return {
    key,
    label,
    type: 'number',
    min,
    max,
    step,
  };
};

function def(
  partial: Omit<IndicatorDef, 'shortLabel'> & { shortLabel?: string },
): IndicatorDef {
  return {
    shortLabel: partial.shortLabel ?? partial.label,
    ...partial,
  };
}

export const INDICATOR_DEFS: Record<IndicatorId, IndicatorDef> = {
  sma: def({
    id: 'sma',
    label: 'Simple Moving Average',
    shortLabel: 'SMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
  }),
  ema: def({
    id: 'ema',
    label: 'Exponential Moving Average',
    shortLabel: 'EMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
  }),
  wma: def({
    id: 'wma',
    label: 'Weighted Moving Average',
    shortLabel: 'WMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
  }),
  hma: def({
    id: 'hma',
    label: 'Hull Moving Average',
    shortLabel: 'HMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 16 },
    fields: [period(16)],
    seriesCount: 1,
  }),
  vwma: def({
    id: 'vwma',
    label: 'Volume Weighted MA',
    shortLabel: 'VWMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
  }),
  dema: def({
    id: 'dema',
    label: 'Double EMA',
    shortLabel: 'DEMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
  }),
  tema: def({
    id: 'tema',
    label: 'Triple EMA',
    shortLabel: 'TEMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
  }),
  rma: def({
    id: 'rma',
    label: 'Wilder / RMA',
    shortLabel: 'RMA',
    category: 'Moving Averages',
    placement: 'overlay',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 1,
  }),
  bb: def({
    id: 'bb',
    label: 'Bollinger Bands',
    shortLabel: 'BB',
    category: 'Volatility',
    placement: 'overlay',
    defaultParams: { period: 20, stdDev: 2 },
    fields: [period(20), numField('stdDev', 'Std Dev', 2, 0.1, 10, 0.1)],
    seriesCount: 3,
  }),
  keltner: def({
    id: 'keltner',
    label: 'Keltner Channels',
    shortLabel: 'KC',
    category: 'Volatility',
    placement: 'overlay',
    defaultParams: { period: 20, atrPeriod: 10, multiplier: 2 },
    fields: [
      period(20),
      numField('atrPeriod', 'ATR Period', 10, 1, 200, 1),
      numField('multiplier', 'Multiplier', 2, 0.1, 10, 0.1),
    ],
    seriesCount: 3,
  }),
  donchian: def({
    id: 'donchian',
    label: 'Donchian Channels',
    shortLabel: 'DC',
    category: 'Volatility',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 3,
  }),
  envelopes: def({
    id: 'envelopes',
    label: 'MA Envelopes',
    shortLabel: 'Env',
    category: 'Volatility',
    placement: 'overlay',
    defaultParams: { period: 20, percent: 0.5 },
    fields: [period(20), numField('percent', 'Percent %', 0.5, 0.01, 20, 0.01)],
    seriesCount: 3,
  }),
  supertrend: def({
    id: 'supertrend',
    label: 'Supertrend',
    shortLabel: 'ST',
    category: 'Trend',
    placement: 'overlay',
    defaultParams: { period: 10, multiplier: 3 },
    fields: [period(10), numField('multiplier', 'Multiplier', 3, 0.5, 20, 0.1)],
    seriesCount: 2,
  }),
  psar: def({
    id: 'psar',
    label: 'Parabolic SAR',
    shortLabel: 'PSAR',
    category: 'Trend',
    placement: 'overlay',
    defaultParams: { period: 2, step: 0.02, max: 0.2 },
    fields: [
      numField('step', 'Step', 0.02, 0.001, 0.5, 0.001),
      numField('max', 'Max', 0.2, 0.01, 1, 0.01),
    ],
    seriesCount: 1,
  }),
  ichimoku: def({
    id: 'ichimoku',
    label: 'Ichimoku Cloud',
    shortLabel: 'Ichimoku',
    category: 'Trend',
    placement: 'overlay',
    defaultParams: { period: 26, tenkan: 9, kijun: 26, senkou: 52 },
    fields: [
      numField('tenkan', 'Tenkan', 9, 1, 100, 1),
      numField('kijun', 'Kijun', 26, 1, 200, 1),
      numField('senkou', 'Senkou B', 52, 1, 300, 1),
    ],
    seriesCount: 4,
  }),
  vwap: def({
    id: 'vwap',
    label: 'VWAP',
    shortLabel: 'VWAP',
    category: 'Volume',
    placement: 'overlay',
    defaultParams: { period: 1, anchor: 'session' },
    fields: [
      {
        key: 'anchor',
        label: 'Anchor',
        type: 'select',
        options: [
          { value: 'session', label: 'Session (daily)' },
          { value: 'all', label: 'Entire window' },
        ],
      },
    ],
    seriesCount: 1,
  }),
  linearreg: def({
    id: 'linearreg',
    label: 'Linear Regression',
    shortLabel: 'LinReg',
    category: 'Trend',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
  }),
  pivot: def({
    id: 'pivot',
    label: 'Pivot Points',
    shortLabel: 'Pivots',
    category: 'Trend',
    placement: 'overlay',
    defaultParams: { period: 20 },
    fields: [numField('period', 'Lookback', 20, 2, 500, 1)],
    seriesCount: 5,
  }),
  atrBands: def({
    id: 'atrBands',
    label: 'ATR Bands',
    shortLabel: 'ATR Bands',
    category: 'Volatility',
    placement: 'overlay',
    defaultParams: { period: 14, multiplier: 2 },
    fields: [period(14), numField('multiplier', 'Multiplier', 2, 0.1, 10, 0.1)],
    seriesCount: 3,
  }),
  rsi: def({
    id: 'rsi',
    label: 'Relative Strength Index',
    shortLabel: 'RSI',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 1,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [30, 70],
  }),
  stoch: def({
    id: 'stoch',
    label: 'Stochastic',
    shortLabel: 'Stoch',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 14, smoothK: 3, smoothD: 3 },
    fields: [
      period(14),
      numField('smoothK', 'Smooth %K', 3, 1, 50, 1),
      numField('smoothD', 'Smooth %D', 3, 1, 50, 1),
    ],
    seriesCount: 2,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [20, 80],
  }),
  stochrsi: def({
    id: 'stochrsi',
    label: 'Stochastic RSI',
    shortLabel: 'StochRSI',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 14, stochPeriod: 14, smoothD: 3 },
    fields: [
      period(14),
      numField('stochPeriod', 'Stoch Period', 14, 1, 100, 1),
      numField('smoothD', 'Smooth %D', 3, 1, 50, 1),
    ],
    seriesCount: 2,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [20, 80],
  }),
  cci: def({
    id: 'cci',
    label: 'Commodity Channel Index',
    shortLabel: 'CCI',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
    scaleMode: 'auto',
    levels: [100, -100],
  }),
  willr: def({
    id: 'willr',
    label: 'Williams %R',
    shortLabel: '%R',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 1,
    scaleMode: 'fixed',
    fixedMin: -100,
    fixedMax: 0,
    levels: [-20, -80],
  }),
  momentum: def({
    id: 'momentum',
    label: 'Momentum',
    shortLabel: 'Mom',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 10 },
    fields: [period(10)],
    seriesCount: 1,
    scaleMode: 'auto',
    levels: [0],
  }),
  roc: def({
    id: 'roc',
    label: 'Rate of Change',
    shortLabel: 'ROC',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 12 },
    fields: [period(12)],
    seriesCount: 1,
    scaleMode: 'auto',
    levels: [0],
  }),
  macd: def({
    id: 'macd',
    label: 'MACD',
    shortLabel: 'MACD',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 26, fast: 12, slow: 26, signal: 9 },
    fields: [
      numField('fast', 'Fast', 12, 1, 100, 1),
      numField('slow', 'Slow', 26, 1, 200, 1),
      numField('signal', 'Signal', 9, 1, 100, 1),
    ],
    seriesCount: 3,
    scaleMode: 'auto',
    levels: [0],
  }),
  ppo: def({
    id: 'ppo',
    label: 'Percentage Price Oscillator',
    shortLabel: 'PPO',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 26, fast: 12, slow: 26, signal: 9 },
    fields: [
      numField('fast', 'Fast', 12, 1, 100, 1),
      numField('slow', 'Slow', 26, 1, 200, 1),
      numField('signal', 'Signal', 9, 1, 100, 1),
    ],
    seriesCount: 3,
    scaleMode: 'auto',
    levels: [0],
  }),
  trix: def({
    id: 'trix',
    label: 'TRIX',
    shortLabel: 'TRIX',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 15 },
    fields: [period(15)],
    seriesCount: 1,
    scaleMode: 'auto',
    levels: [0],
  }),
  adx: def({
    id: 'adx',
    label: 'Average Directional Index',
    shortLabel: 'ADX',
    category: 'Trend',
    placement: 'pane',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 3,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [20, 40],
  }),
  aroon: def({
    id: 'aroon',
    label: 'Aroon',
    shortLabel: 'Aroon',
    category: 'Trend',
    placement: 'pane',
    defaultParams: { period: 25 },
    fields: [period(25)],
    seriesCount: 2,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [50],
  }),
  ao: def({
    id: 'ao',
    label: 'Awesome Oscillator',
    shortLabel: 'AO',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 34 },
    fields: [],
    seriesCount: 1,
    scaleMode: 'auto',
    levels: [0],
  }),
  ultimate: def({
    id: 'ultimate',
    label: 'Ultimate Oscillator',
    shortLabel: 'UO',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 28, period1: 7, period2: 14, period3: 28 },
    fields: [
      numField('period1', 'Period 1', 7, 1, 50, 1),
      numField('period2', 'Period 2', 14, 1, 100, 1),
      numField('period3', 'Period 3', 28, 1, 200, 1),
    ],
    seriesCount: 1,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [30, 70],
  }),
  vortex: def({
    id: 'vortex',
    label: 'Vortex Indicator',
    shortLabel: 'VI',
    category: 'Trend',
    placement: 'pane',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 2,
    scaleMode: 'auto',
    levels: [1],
  }),
  chop: def({
    id: 'chop',
    label: 'Choppiness Index',
    shortLabel: 'CHOP',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 1,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [38.2, 61.8],
  }),
  mfi: def({
    id: 'mfi',
    label: 'Money Flow Index',
    shortLabel: 'MFI',
    category: 'Volume',
    placement: 'pane',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 1,
    scaleMode: 'fixed',
    fixedMin: 0,
    fixedMax: 100,
    levels: [20, 80],
  }),
  obv: def({
    id: 'obv',
    label: 'On Balance Volume',
    shortLabel: 'OBV',
    category: 'Volume',
    placement: 'pane',
    defaultParams: { period: 1 },
    fields: [],
    seriesCount: 1,
    scaleMode: 'auto',
  }),
  adline: def({
    id: 'adline',
    label: 'Accumulation / Distribution',
    shortLabel: 'A/D',
    category: 'Volume',
    placement: 'pane',
    defaultParams: { period: 1 },
    fields: [],
    seriesCount: 1,
    scaleMode: 'auto',
  }),
  cmf: def({
    id: 'cmf',
    label: 'Chaikin Money Flow',
    shortLabel: 'CMF',
    category: 'Volume',
    placement: 'pane',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
    scaleMode: 'auto',
    levels: [0],
  }),
  atr: def({
    id: 'atr',
    label: 'Average True Range',
    shortLabel: 'ATR',
    category: 'Volatility',
    placement: 'pane',
    defaultParams: { period: 14 },
    fields: [period(14)],
    seriesCount: 1,
    scaleMode: 'auto',
  }),
  stddev: def({
    id: 'stddev',
    label: 'Standard Deviation',
    shortLabel: 'StdDev',
    category: 'Volatility',
    placement: 'pane',
    defaultParams: { period: 20 },
    fields: [period(20)],
    seriesCount: 1,
    scaleMode: 'auto',
  }),
  fisher: def({
    id: 'fisher',
    label: 'Fisher Transform',
    shortLabel: 'Fisher',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 10 },
    fields: [period(10)],
    seriesCount: 2,
    scaleMode: 'auto',
    levels: [0],
  }),
  elderRay: def({
    id: 'elderRay',
    label: 'Elder Ray',
    shortLabel: 'Elder',
    category: 'Oscillators',
    placement: 'pane',
    defaultParams: { period: 13 },
    fields: [period(13)],
    seriesCount: 2,
    scaleMode: 'auto',
    levels: [0],
  }),
  fvg: def({
    id: 'fvg',
    label: 'ICT Fair Value Gap',
    shortLabel: 'FVG',
    category: 'ICT',
    placement: 'overlay',
    defaultParams: { period: 50, lookback: 50 },
    fields: [numField('lookback', 'Lookback bars', 50, 10, 500, 1)],
    seriesCount: 2,
  }),
  orderBlock: def({
    id: 'orderBlock',
    label: 'ICT Order Block',
    shortLabel: 'OB',
    category: 'ICT',
    placement: 'overlay',
    defaultParams: { period: 3, swing: 3 },
    fields: [numField('swing', 'Swing length', 3, 1, 20, 1)],
    seriesCount: 4,
  }),
  liquidity: def({
    id: 'liquidity',
    label: 'ICT Liquidity (BSL/SSL)',
    shortLabel: 'Liquidity',
    category: 'ICT',
    placement: 'overlay',
    defaultParams: { period: 5, swing: 5 },
    fields: [numField('swing', 'Swing length', 5, 1, 30, 1)],
    seriesCount: 2,
  }),
  premiumDiscount: def({
    id: 'premiumDiscount',
    label: 'ICT Premium / Discount',
    shortLabel: 'P/D',
    category: 'ICT',
    placement: 'overlay',
    defaultParams: { period: 10, swing: 10 },
    fields: [numField('swing', 'Swing length', 10, 2, 50, 1)],
    seriesCount: 5,
  }),
  killzone: def({
    id: 'killzone',
    label: 'ICT Killzones (London/NY)',
    shortLabel: 'KZ',
    category: 'ICT',
    placement: 'overlay',
    defaultParams: {
      period: 1,
      londonStart: 7,
      londonEnd: 10,
      nyStart: 12,
      nyEnd: 15,
    },
    fields: [
      numField('londonStart', 'London start (UTC)', 7, 0, 23, 1),
      numField('londonEnd', 'London end (UTC)', 10, 0, 23, 1),
      numField('nyStart', 'NY start (UTC)', 12, 0, 23, 1),
      numField('nyEnd', 'NY end (UTC)', 15, 0, 23, 1),
    ],
    seriesCount: 2,
  }),
  bosChoch: def({
    id: 'bosChoch',
    label: 'ICT BOS / CHoCH',
    shortLabel: 'BOS',
    category: 'ICT',
    placement: 'overlay',
    defaultParams: { period: 5, swing: 5 },
    fields: [numField('swing', 'Swing length', 5, 1, 30, 1)],
    seriesCount: 1,
  }),
  ote: def({
    id: 'ote',
    label: 'ICT Optimal Trade Entry',
    shortLabel: 'OTE',
    category: 'ICT',
    placement: 'overlay',
    defaultParams: { period: 8, swing: 8, fibLow: 0.618, fibHigh: 0.79 },
    fields: [
      numField('swing', 'Swing length', 8, 2, 40, 1),
      numField('fibLow', 'Fib low', 0.618, 0.1, 1, 0.001),
      numField('fibHigh', 'Fib high', 0.79, 0.1, 1, 0.001),
    ],
    seriesCount: 2,
  }),
};

export const INDICATOR_ORDER: IndicatorId[] = Object.keys(INDICATOR_DEFS) as IndicatorId[];

export const INDICATOR_CATEGORIES = [
  'Moving Averages',
  'Volatility',
  'Oscillators',
  'Trend',
  'Volume',
  'ICT',
] as const;

export function getIndicatorDef(id: IndicatorId): IndicatorDef {
  return INDICATOR_DEFS[id];
}

export function formatIndicatorLabel(id: IndicatorId, params: Record<string, number | string | boolean>): string {
  const d = INDICATOR_DEFS[id];
  const parts = d.fields
    .filter((f) => f.type === 'number')
    .slice(0, 3)
    .map((f) => {
      const v = params[f.key] ?? d.defaultParams[f.key];
      return typeof v === 'number' ? (Number.isInteger(v) ? String(v) : v.toFixed(2)) : String(v);
    });
  return parts.length ? `${d.shortLabel} ${parts.join(',')}` : d.shortLabel;
}
