/** Metric catalog — id, key, label, formula, minSampleSize (§3, §7). */

export interface MetricDef {
  id: number;
  key: string;
  label: string;
  group: string;
  formula: string;
  minSampleSize: number;
  unit?: string;
}

export const METRIC_CATALOG: MetricDef[] = [
  { id: 1, key: 'netPnl', label: 'Net P&L', group: 'A', formula: 'Σ netPnl_i', minSampleSize: 1, unit: 'ccy' },
  { id: 2, key: 'grossProfit', label: 'Gross profit', group: 'A', formula: 'Σ netPnl_i where > 0', minSampleSize: 1, unit: 'ccy' },
  { id: 3, key: 'grossLoss', label: 'Gross loss', group: 'A', formula: 'Σ netPnl_i where < 0', minSampleSize: 1, unit: 'ccy' },
  { id: 4, key: 'profitFactor', label: 'Profit factor', group: 'A', formula: 'grossProfit / |grossLoss|', minSampleSize: 30 },
  { id: 5, key: 'totalReturnPct', label: 'Total return %', group: 'A', formula: 'netPnl / initialBalance × 100', minSampleSize: 1, unit: '%' },
  { id: 6, key: 'totalCommission', label: 'Total commission', group: 'A', formula: 'Σ commission_i', minSampleSize: 1, unit: 'ccy' },
  { id: 7, key: 'totalSwap', label: 'Total swap', group: 'A', formula: 'Σ swap_i', minSampleSize: 1, unit: 'ccy' },
  { id: 8, key: 'totalCosts', label: 'Total costs', group: 'A', formula: 'commission + |swap|', minSampleSize: 1, unit: 'ccy' },
  { id: 9, key: 'costDragPct', label: 'Cost drag %', group: 'A', formula: 'totalCosts / |grossPnl| × 100', minSampleSize: 20, unit: '%' },
  { id: 10, key: 'netToGross', label: 'Net-to-gross ratio', group: 'A', formula: 'netPnl / grossPnl', minSampleSize: 20 },
  { id: 11, key: 'totalTrades', label: 'Total trades', group: 'B', formula: 'N', minSampleSize: 1 },
  { id: 12, key: 'wins', label: 'Wins', group: 'B', formula: 'count(netPnl > 0)', minSampleSize: 1 },
  { id: 13, key: 'losses', label: 'Losses', group: 'B', formula: 'count(netPnl < 0)', minSampleSize: 1 },
  { id: 14, key: 'breakeven', label: 'Breakeven', group: 'B', formula: 'count(netPnl == 0)', minSampleSize: 1 },
  { id: 15, key: 'winRate', label: 'Win rate %', group: 'B', formula: 'W / N × 100', minSampleSize: 20, unit: '%' },
  { id: 16, key: 'longShort', label: 'Long / short trades', group: 'B', formula: 'counts by side', minSampleSize: 1 },
  { id: 17, key: 'longWinRate', label: 'Long win rate %', group: 'B', formula: 'longWins / longs', minSampleSize: 20, unit: '%' },
  { id: 18, key: 'shortWinRate', label: 'Short win rate %', group: 'B', formula: 'shortWins / shorts', minSampleSize: 20, unit: '%' },
  { id: 19, key: 'avgWin', label: 'Average win', group: 'B', formula: 'grossProfit / W', minSampleSize: 10, unit: 'ccy' },
  { id: 20, key: 'avgLoss', label: 'Average loss', group: 'B', formula: '|grossLoss| / L', minSampleSize: 10, unit: 'ccy' },
  { id: 21, key: 'payoff', label: 'Payoff ratio', group: 'B', formula: 'avgWin / avgLoss', minSampleSize: 20 },
  { id: 22, key: 'largestWin', label: 'Largest win', group: 'B', formula: 'max(netPnl)', minSampleSize: 1, unit: 'ccy' },
  { id: 23, key: 'largestLoss', label: 'Largest loss', group: 'B', formula: 'min(netPnl)', minSampleSize: 1, unit: 'ccy' },
  { id: 24, key: 'totalR', label: 'Total R', group: 'C', formula: 'Σ R_i (skip NaN)', minSampleSize: 1 },
  { id: 25, key: 'expectancyR', label: 'Expectancy (R)', group: 'C', formula: 'mean(R_i)', minSampleSize: 30 },
  { id: 26, key: 'expectancyCcy', label: 'Expectancy (currency)', group: 'C', formula: 'netPnl / N', minSampleSize: 30, unit: 'ccy' },
  { id: 27, key: 'rStd', label: 'R standard deviation', group: 'C', formula: 'Welford sd(R)', minSampleSize: 30 },
  { id: 28, key: 'sqn', label: 'SQN', group: 'C', formula: '√N × mean(R) / sd(R)', minSampleSize: 30 },
  { id: 29, key: 'expectancyPerR', label: 'Expectancy per unit risk', group: 'C', formula: 'mean(R)', minSampleSize: 30 },
  { id: 30, key: 'kelly', label: 'Kelly %', group: 'C', formula: 'WR − (1−WR)/payoff', minSampleSize: 50, unit: '%' },
  { id: 31, key: 'optimalF', label: 'Optimal-f (capped)', group: 'C', formula: 'Kelly capped at 25%, floored at 0', minSampleSize: 50, unit: '%' },
  { id: 32, key: 'riskOfRuin', label: 'Risk of ruin', group: 'C', formula: 'MC 10k paths, seeded', minSampleSize: 50, unit: '%' },
  { id: 33, key: 'tradesForSig', label: 'Trades needed for significance', group: 'C', formula: '(sd(R)×1.96/mean(R))²', minSampleSize: 30 },
  { id: 34, key: 'returnStd', label: 'Return std dev (daily)', group: 'D', formula: 'Welford sd(daily returns)', minSampleSize: 30 },
  { id: 35, key: 'downsideDev', label: 'Downside deviation', group: 'D', formula: 'Welford over min(r,0)', minSampleSize: 30 },
  { id: 36, key: 'sharpe', label: 'Sharpe (daily, annualized)', group: 'D', formula: '(meanDaily−rf)/sdDaily×√periodsPerYear', minSampleSize: 60 },
  { id: 37, key: 'sortino', label: 'Sortino (daily, annualized)', group: 'D', formula: 'meanDaily/downsideDev×√ppy', minSampleSize: 60 },
  { id: 38, key: 'calmar', label: 'Calmar ratio', group: 'D', formula: 'CAGR / maxDrawdownPct', minSampleSize: 1 },
  { id: 39, key: 'sterling', label: 'Sterling ratio', group: 'D', formula: 'CAGR / avgAnnualMaxDD', minSampleSize: 1 },
  { id: 40, key: 'recoveryFactor', label: 'Recovery factor', group: 'D', formula: 'netPnl / maxDrawdown', minSampleSize: 30 },
  { id: 41, key: 'ulcer', label: 'Ulcer index', group: 'D', formula: '√mean(drawdownPct²)', minSampleSize: 30 },
  { id: 42, key: 'martin', label: 'Martin ratio', group: 'D', formula: 'CAGR / ulcerIndex', minSampleSize: 1 },
  { id: 43, key: 'cagr', label: 'CAGR', group: 'D', formula: '(end/start)^(365/days)−1', minSampleSize: 1, unit: '%' },
  { id: 44, key: 'skewness', label: 'Skewness (R)', group: 'D', formula: '3rd standardized moment', minSampleSize: 50 },
  { id: 45, key: 'kurtosis', label: 'Kurtosis excess (R)', group: 'D', formula: '4th moment − 3', minSampleSize: 100 },
  { id: 46, key: 'maxDd', label: 'Max drawdown', group: 'E', formula: 'max(peak−equity)', minSampleSize: 1, unit: 'ccy' },
  { id: 47, key: 'maxDdPct', label: 'Max drawdown % (closed equity)', group: 'E', formula: 'max((peak−eq)/peak)', minSampleSize: 1, unit: '%' },
  { id: 48, key: 'maxDdDuration', label: 'Max DD duration (days)', group: 'E', formula: 'longest below peak', minSampleSize: 1 },
  { id: 49, key: 'currentDd', label: 'Current drawdown %', group: 'E', formula: '(peak−now)/peak', minSampleSize: 1, unit: '%' },
  { id: 50, key: 'avgDd', label: 'Average drawdown', group: 'E', formula: 'mean of DD episodes', minSampleSize: 10 },
  { id: 51, key: 'ddEpisodes', label: 'Drawdown episodes', group: 'E', formula: 'peak-to-recovery cycles', minSampleSize: 1 },
  { id: 52, key: 'timeInDd', label: 'Time in drawdown %', group: 'E', formula: 'daysBelowPeak/totalDays', minSampleSize: 30, unit: '%' },
  { id: 53, key: 'maxRunUp', label: 'Max run-up', group: 'E', formula: 'max(equity−trough)', minSampleSize: 1, unit: 'ccy' },
  { id: 54, key: 'recoveryTime', label: 'Recovery from max DD (days)', group: 'E', formula: 'peak→recovery or null', minSampleSize: 1 },
  { id: 55, key: 'longestFlat', label: 'Longest flat (days)', group: 'E', formula: 'no new equity high', minSampleSize: 30 },
  { id: 56, key: 'maxConsecWins', label: 'Max consecutive wins', group: 'F', formula: 'run-length', minSampleSize: 1 },
  { id: 57, key: 'maxConsecLosses', label: 'Max consecutive losses', group: 'F', formula: 'run-length', minSampleSize: 1 },
  { id: 58, key: 'avgWinStreak', label: 'Average win streak', group: 'F', formula: 'mean win run length', minSampleSize: 20 },
  { id: 59, key: 'avgLossStreak', label: 'Average loss streak', group: 'F', formula: 'mean loss run length', minSampleSize: 20 },
  { id: 60, key: 'currentStreak', label: 'Current streak', group: 'F', formula: 'signed run at end', minSampleSize: 1 },
  { id: 61, key: 'winningDaysPct', label: 'Winning days %', group: 'F', formula: 'positive days / trading days', minSampleSize: 30, unit: '%' },
  { id: 62, key: 'bestWorstDay', label: 'Best / worst day', group: 'F', formula: 'max / min daily net', minSampleSize: 20, unit: 'ccy' },
  { id: 63, key: 'monthlyRetStd', label: 'Monthly return std dev', group: 'F', formula: 'sd of monthly returns', minSampleSize: 6 },
  { id: 64, key: 'profitableMonths', label: 'Profitable months %', group: 'F', formula: 'positive months / months', minSampleSize: 6, unit: '%' },
  { id: 65, key: 'avgHold', label: 'Average hold time', group: 'G', formula: 'mean(durationSec)', minSampleSize: 10 },
  { id: 66, key: 'avgHoldWins', label: 'Avg hold — winners', group: 'G', formula: 'mean duration of wins', minSampleSize: 10 },
  { id: 67, key: 'avgHoldLosses', label: 'Avg hold — losers', group: 'G', formula: 'mean duration of losses', minSampleSize: 10 },
  { id: 68, key: 'longestShortest', label: 'Longest / shortest trade', group: 'G', formula: 'max / min duration', minSampleSize: 1 },
  { id: 69, key: 'tradesPerDay', label: 'Trades per day', group: 'G', formula: 'N / tradingDays', minSampleSize: 20 },
  { id: 70, key: 'timeInMarket', label: 'Time in market %', group: 'G', formula: 'Σ duration / span', minSampleSize: 20, unit: '%' },
  { id: 71, key: 'byHour', label: 'Performance by hour', group: 'G', formula: '24 buckets', minSampleSize: 5 },
  { id: 72, key: 'byWeekday', label: 'Performance by weekday', group: 'G', formula: '7 buckets', minSampleSize: 5 },
  { id: 73, key: 'bySession', label: 'Performance by session', group: 'G', formula: 'Asia/London/NY/overlap (UTC)', minSampleSize: 10 },
  { id: 74, key: 'byMonth', label: 'Performance by month', group: 'G', formula: 'calendar month buckets', minSampleSize: 1 },
  { id: 75, key: 'avgMfeR', label: 'Average MFE (R)', group: 'H', formula: 'mean favorable excursion R', minSampleSize: 20 },
  { id: 76, key: 'avgMaeR', label: 'Average MAE (R)', group: 'H', formula: 'mean adverse excursion R', minSampleSize: 20 },
  { id: 77, key: 'tradeEfficiency', label: 'Trade efficiency %', group: 'H', formula: 'mean (exit−entry)/(mfe−entry)', minSampleSize: 20, unit: '%' },
  { id: 78, key: 'entryEfficiency', label: 'Entry efficiency %', group: 'H', formula: 'blocked — needs bar OHLC at entry', minSampleSize: 20, unit: '%' },
  { id: 79, key: 'exitEfficiency', label: 'Exit efficiency %', group: 'H', formula: 'alias of trade efficiency', minSampleSize: 20, unit: '%' },
  { id: 80, key: 'exitBreakdown', label: 'Exit reason breakdown', group: 'H', formula: '% TP/SL/manual/stop-out/trailing', minSampleSize: 20 },
  { id: 81, key: 'ambiguousPct', label: 'Ambiguous fill %', group: 'H', formula: 'count(ambiguous)/N×100', minSampleSize: 1, unit: '%' },
  { id: 82, key: 'maeWinnersR', label: 'MAE of winners (R)', group: 'H', formula: 'heat taken by winners', minSampleSize: 20 },
  { id: 83, key: 'byTag', label: 'Performance by tag', group: 'I', formula: 'per tag N/WR/E[R]/PF', minSampleSize: 20 },
  { id: 84, key: 'bySymbol', label: 'Performance by symbol', group: 'I', formula: 'per symbol stats', minSampleSize: 20 },
  { id: 85, key: 'riskConsistency', label: 'Risk consistency', group: 'I', formula: 'sd of |R| risk proxy', minSampleSize: 20 },
  { id: 86, key: 'oversizingRate', label: 'Oversizing rate', group: 'I', formula: 'risk > 1.5× median', minSampleSize: 20, unit: '%' },
  { id: 87, key: 'postLoss', label: 'Post-loss behavior', group: 'I', formula: 'WR/risk after loss vs baseline', minSampleSize: 30 },
  { id: 88, key: 'ruleAdherence', label: 'Rule adherence %', group: 'I', formula: 'trades with required tags / N', minSampleSize: 20, unit: '%' },
];
